name: Auto Sync # 每天自动同步我仓库的代码

on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * *'


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true
        token: ${{ secrets.PAT }} # 参考 https://blog.csdn.net/weixin_46897467/article/details/113106403 申请到token后添加进secret内 Name填写PAT Value填写token的字符串

    - name: Set git identity
      run : |
        git config --global user.email "chiupam@126.com"
        git config --global user.name "chiupam"
    - name: Load upstream commits
      run: |
        git pull https://github.com/chiupam/Epidemic.git --log --no-commit
    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
        TZ: Asia/Shanghai
      run: git push origin $DOWNSTREAM_BRANCH
